language: java

os: linux

dist: xenial

install: true

jdk: openjdk8

services:
    - xvfb

git:
    depth: false

before_script:
    - export DISPLAY=:99.0

addons:
    chrome: stable
    firefox: latest
    sonarcloud:
        organization: "bonigarcia-github"
        token:
            secure: "lgqsgEKHl4faQb+Dnqd/fq/y4v69ThpMqSVNFixS54b314OKhTOjd40x+0/UXretZ5IG2y60wQKvlNAQoCaaEUBFosNjcv5dBkoOOKadbv/jwNPbxaWkAnmd2NfXq4iYTPiFPki/bSH6UZ+kWSDSgsBGSUQOw18FCfHiuYCo1YcfjCrqePJrGXnqFRQQhA6tZYBhSFVhTCJIYZ32NjIo2qXl64sniaN+gqhag6VFD9WLHU6SbZbQ/FMNJKv3TfXzYv4r0KIjq5sI4RV1bpUV5XEI9H8iTFDUkGQ7Mg2sYmsPRGQwetYfZWaOBD2n5Hqmfzu97imj9sS1WFCJziHXGBA5SVy9p6SAR0elm00hpCqw8RumZZKcV1tSHBhGdToTDMxbjfuDDiAnkxykW2OthWcKFFpxnvue7CPG1LxNOAVEDnA1ZYKO8b6OuQr6Q7vOZnKRvEBdbkJT/b/ORMrlBjfZ48Q4/egsnkNRk12qXD3kMun6Q7fH0qX0hpBkbK+V8gOi5AUpRgccGrOcF4QZA/pB0iN//EgZKK+7oyW697roDRe19ucCMGP7jeKdVGT+KpJG/vius9rrt5i0B71ojNnSbPuSsa0xt7/Ov7sDFqsdR7uhcJ+6q26Soa6KvZKm66j50yz/NglswRAaOC2y51b300JYIytHHTfTr/toLYA="

jobs:
    include:
        - stage: Gradle
          script: ./gradlew test
        - stage: Maven
          script: mvn test sonar:sonar && bash <(curl -s https://codecov.io/bash)
